### ISSUE TITLE
Status report error shown for unsupported localgov_paragraphs version

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_publications#133]
This may be more of a localgov_paragraphs issue, so we need to decide where to resolve this.
On installing localgov_publications, there is now an error that an unsupported version of localgov_paragraphs is installed.

<img width="1074" alt="Screenshot 2024-01-10 at 10 01 39 am" src="https://github.com/localgovdrupal/localgov_publications/assets/1467480/321b0de7-0520-4132-9c33-e399152f4a91">

This happens becuase localgov_paragraphs (and all localgov drupal modules) don't declare their version in module.info.yml. This is normally done during release if a module is released on Drupal.org.

I suggest removing the requirement in localgov_publications.info.yml for now as the requirement is already present in composer.json.

We could also add the version to localgov_paragraphs.info.yml.
```yaml
name: LocalGov Paragraphs
description: Provides core paragraph components for the LocalGov Drupal distribution.
package: LocalGov Drupal
type: module
core_version_requirement: ^9 || ^10
version: '2.3.2'
```
However that means it does have to be updated each time.

In the future we need to decide how we might handle this, and is a good argument in favour of moving at least release version of the modules to Drupal.org.
